name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build self contained
      run: dotnet publish Ets2SyncWindows/Ets2SyncWindows.csproj -o publish/self-contained/ -f netcoreapp3.1 -r win-x64 -c Release --self-contained -p:PublishSingleFile=true
    - name: Build net core dependant
      run: dotnet publish Ets2SyncWindows/Ets2SyncWindows.csproj -o publish/core/ -f netcoreapp3.1 -r win-x64 -c Release --no-self-contained -p:PublishSingleFile=true
